### PR TITLE
Auto logout

### PR DESCRIPTION
**Pull request by larskendall**
Automatically logs user out after the time specified in the `AUTO_LOGOUT_SECONDS` environment variable. When no activity is detected for long enough, a warning should be displayed with a countdown, giving the user a chance to stay logged in by pressing the button. The time at which the warning is displayed is set in the `AUTO_LOGOUT_WARNING_AT_SECONDS_LEFT` environment variable.

By default, auto logout is disabled, with an auto logout time of 30 minutes set in the manifest file.

Pings to notify the server of user activity are capped at 1 per minute. However, after 1 minute has passed, a user activity ping will be sent immediately as soon as any input is detected. In order to properly test auto logout, I would recommend either setting the auto logout times above one minute, or dropping the ping cap down to 1 second if you'd rather set a small auto logout time. Otherwise, user activity may not be reported in time to stop an auto logout. The ping time can be set in the `handleUserActiveInput()` function in `Application.js`.

@jsvrcek I ended up going ahead with the separate endpoint to report user activity, since piggybacking on the auth endpoint started getting a little inelegant in the frontend code.

selection_013
selection_014

### CODE REVIEW

**Comment by larskendall** [comment]
I spent a little time trying to come up with something useful for testing this stuff, but it was a bit tricky. I'll give it some more thought though to see if I can come up with something. I can probably at least add some very basic tests for the UI.

**Comment by larskendall** [comment]
@lukerees I got a couple tests written to at least verify the state changes. I was having trouble verifying that the dialogs were actually showing though. Couldn't find much help about that online either. Let me know if you know a good solution for that or if you have any ideas for other good tests.

**Comment by lukerees** [comment]
Okay great. Yes I should have mentioned not to worry too much about the dialogs. Those are a real pain in the butt, anything I've put together to test them in the past has been sorta hacky (mounting the props as its own wrapper 😬 ). I think its because all the sub elements of the dialog get mounted somewhere outside the scope of the actual test wrapper. The unit tests you added for the auto logout functions are good, thanks. Could you just add tests for the new user action? You should be able to model it off of the other axios related tests in userActions.spec.js. I think once we get that in there we will have some good basic coverage for everything and then we can go ahead and get this merged 👍. (sorry I know im being a real stickler for tests here)

**Comment by larskendall** [comment]
Cool, no problem. Thanks for catching the user action thing.

**Comment by larskendall** [comment]
@lukerees Got that user active action test added.

**Pull request merged**
