### PR TITLE
Map zoom level

### PR DESCRIPTION
**Pull request by larskendall**
Ignore the branch name - the map slider was removed in favor of only showing the zoom level. However, I left the utility functions in for creating and destroying the map slider, as well as the css, in case we want to restore it in the future.

You should see your current zoom level in the bottom right of the large maps.

selection_034

### CODE REVIEW

**Comment by lukerees** [comment]
Hey Lars this looks good! The only thing I noticed was an overlap with the AOI info popup on the create page.
image

Im not sure if this is something we want to handle or how we would want to handle it. I suppose we could just hide the zoom level under the popup if need be, but then again what if users will want to see the zoom level AND the info popup.

**Comment by larskendall** [comment]
@lukerees This should be fixed now. I shortened the attribution text to "© OpenStreetMap" and bumped the zoom level into the bottom right below screen widths of 640px. I discussed both changes with Josh to make sure they were okay.

**Comment by lukerees** [comment]
@larskendall I like the way you handled it, very clean looking 👍 
It does look like the css change also bumps the scalebar over in minimaps where we dont display the zoom level (datapackpage gridview for example). I think you might need to go in and make sure that css rule is only applied to the MapView and Create page. Otherwise looks great!

**Comment by larskendall** [comment]
@lukerees This should be fixed now. Thanks for catching that issue!

**Pull request merged**
