### PR TITLE
320 datapack permissions

### PR DESCRIPTION
**Pull request by david-sherman**
This branch adds job permissions support to the job api.    Initial ADMIN permission is  assigned to the user who creates the job.  Permissions for users and groups can be adjusted via the Patch command.

Also, new tests have been added to the job view

### CODE REVIEW

**Comment by lukerees** [comment]
@david-sherman I dont think this branch is ready for a PR, there are still lots of things that need to be sorted out. Ill try to summarize what I found, so you can test, confirm, and fix if needed.
1. We need the permissions to be listed with the job in the `/api/runs` api as well, since often we get the runs and need to get the job information there, instead of requesting the job information from `/api/jobs`.
2. When I PATCH with just users or just groups in the permissions object I get a key error. It would be nice to only have to include one if I am not updating the other.
3. When an unauthorized user makes a PATCH request a 403 is returned with body `{ success: false }`. It would be nice for it to return a more verbose message. You can see examples of the error message format we use in other parts of the api views. The 403 is a good indication of failure, but we need a message to display in the UI.
4. When I PATCHED both permissions and publish, it returned: `{ success: true, published: false }`. It is confusing to get back an object that contains one of the updated fields, and then a success key for the other field.
5. Viewing permissions seem to be fundamentally broken. The API does not seem to be returning the job to users who have been given permissions to view it. After adding a group and several users to the job permissions and making the job private, I could only see the job when logged in as admin (the creator of the job). When I made the job 'public' everyone could view it again. It seems as though there is no reconciliation between public/private and the permissions set on a job. As-is we still only have public and private working, there is no concept of specially granted permissions. Maybe I was doing something wrong? If so let me know.

I think that is all for now, thanks!

**Comment by david-sherman** [comment]
Thanks for the external testing.  I'll review, fix where I can and get back to you with questions.

**Comment by david-sherman** [comment]
Hi.  1 through 4 should be straightforward most are simple bugs.   However,  5 was not implemented  - yet.   Lets discuss - Its pretty clear what needs to be done, but lets review on Monday.

**Comment by lukerees** [comment]
Okay sounds good, thanks David!

**Comment by david-sherman** [comment]
This branch has been  abandonded.

**Pull request closed without merging**
